# Generated by Django 4.1.5 on 2023-01-27 08:47

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ManagerAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('manager', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pusers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('role', models.CharField(choices=[('OILC_Manager', 'OILC_Manager'), ('Deployed_Manager', 'Deployed_Manager'), ('Employee', 'Employee'), ('admin', 'admin')], max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='RoleAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='SeverityAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('severity', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='StatusAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TypeAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='TicketAPI',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(default='OJ-', max_length=20, unique=True)),
                ('Subject', models.CharField(max_length=100)),
                ('Remarks', models.TextField()),
                ('Admin_comment', models.CharField(default='', max_length=100)),
                ('Mgr_comment', models.CharField(default='', max_length=100)),
                ('request_raised_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('Report_To', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.managerapi')),
                ('Severity', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.severityapi')),
                ('Status', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.statusapi')),
                ('Type', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.typeapi')),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_no', models.CharField(default='OJ-', max_length=20, unique=True)),
                ('Subject', models.CharField(max_length=100)),
                ('Severity', models.CharField(choices=[('high', 'high'), ('medium', 'medium'), ('low', 'low')], max_length=100)),
                ('Type', models.CharField(choices=[('hardware', 'hardware'), ('software', 'software'), ('cubical', 'cubical'), ('conference room', 'conference room'), ('stationary', 'stationary'), ('other', 'other')], max_length=100)),
                ('Report_To', models.CharField(choices=[('OILC_Manager', 'OILC_Manager'), ('Deployed_Manager', 'Deployed_Manager')], max_length=100)),
                ('Remarks', models.TextField()),
                ('Status', models.CharField(choices=[('raised', 'raised'), ('accepted', 'accepted'), ('rejected', 'rejected'), ('complete', 'complete')], default='raised', max_length=100)),
                ('Admin_comment', models.CharField(default='', max_length=100)),
                ('Mgr_comment', models.CharField(default='', max_length=100)),
                ('request_raised_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
