# Generated by Django 4.1.5 on 2023-01-27 08:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0002_users'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Users',
            new_name='UsersAPI',
        ),
    ]
