# Generated by Django 4.1.5 on 2023-01-27 13:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0003_rename_users_usersapi'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersapi',
            name='role',
            field=models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.roleapi'),
        ),
    ]
