# Generated by Django 4.1.5 on 2023-01-31 12:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0006_alter_usersapi_role'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticketapi',
            name='user',
        ),
        migrations.AlterField(
            model_name='ticketapi',
            name='Status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.statusapi'),
        ),
        migrations.AlterField(
            model_name='ticketapi',
            name='ticket_no',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='usersapi',
            name='role',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.roleapi'),
        ),
    ]
