# Generated by Django 4.1.5 on 2023-01-31 12:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0007_remove_ticketapi_user_alter_ticketapi_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersapi',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.roleapi'),
        ),
    ]
