# Generated by Django 4.1.5 on 2023-01-31 12:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0008_alter_usersapi_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersapi',
            name='role',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.roleapi'),
        ),
    ]
