# Generated by Django 4.1.5 on 2023-01-31 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0009_alter_usersapi_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketapi',
            name='Severity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.severityapi'),
        ),
    ]
