# Generated by Django 4.1.5 on 2023-01-31 12:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0010_alter_ticketapi_severity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketapi',
            name='Report_To',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.managerapi'),
        ),
        migrations.AlterField(
            model_name='ticketapi',
            name='Type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='ticketapp.typeapi'),
        ),
    ]
