# Generated by Django 4.1.5 on 2023-02-02 04:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0011_alter_ticketapi_report_to_alter_ticketapi_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketapi',
            name='Report_To',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.managerapi'),
        ),
        migrations.AlterField(
            model_name='ticketapi',
            name='Severity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.severityapi'),
        ),
        migrations.AlterField(
            model_name='ticketapi',
            name='Type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ticketapp.typeapi'),
        ),
    ]
