# Generated by Django 4.1.5 on 2023-02-07 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0012_alter_ticketapi_report_to_alter_ticketapi_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticketapi',
            name='user',
            field=models.CharField(default='', max_length=30),
        ),
    ]
