# Generated by Django 4.1.5 on 2023-02-08 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ticketapp', '0013_ticketapi_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticketapi',
            name='user',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
